<?php

return [

    // 处理器类型
    'cpu' => [
        'Intel Xeon E5-2699 v4',
        'AMD EPYC 7742',
        'Intel Xeon Platinum 8180M',
        'AMD Ryzen Threadripper 3990X',
        'Intel Core i9-10900K',
    ],
    // 内存
    'member' => [
        '8G',
        '16',
        '32',
        '64',
    ],
    // 内存
    'disk' => [
        '100G',
        '200G',
        '300G',
        '500G',
    ],
    // 系统
    'system' => [
        'Centos 7.1',
        'Centos 7.2',
        'Centos 7.3',
        'Centos 7.4',
        'Centos 7.5',
        'Centos 7.6',
    ],
    // 开发环境系统
    'develop_system' => [
        'Windows 8',
        'Windows 8.1',
        'Windows 10',
        'Windows 11',
        'macOS Sierra 10.12',
        'macOS High Sierra 10.13',
        'macOS Mojave 10.14',
        'macOS Catalina 10.15',
        'macOS Big Sur 11',
        'macOS Monterey 12',
        'macOS Sonoma',
    ],
    // PHP版本
    'php_ver' => [
        'php7.1.1',
        'php7.1.2',
        'php7.1.3',
        'php7.1.4',
        'php7.1.5',
        'php7.1.6',
        'php7.1.7',
        'php7.1.8',
        'php7.1.9',
        'php7.2.1',
        'php7.2.2',
        'php7.2.3',
        'php7.2.4',
        'php7.2.5',
        'php7.2.6',
        'php7.2.7',
        'php7.2.8',
        'php7.2.9',
        'php7.3.1',
        'php7.3.2',
        'php7.3.3',
        'php7.3.4',
        'php7.3.5',
        'php7.3.6',
        'php7.3.7',
        'php7.3.8',
        'php7.3.9',
        'php7.4.1',
        'php7.4.2',
        'php7.4.3',
        'php7.4.4',
        'php7.4.5',
        'php7.4.6',
        'php7.4.7',
        'php7.4.8',
        'php7.4.9',
    ],
    // MYSQL版本
    'mysql_ver' => [
        'mysql5.6',
        'mysql5.7',
        'mysql8.0',
    ],
    // nginx版本
    'nginx_ver' => [
        'nginx1.15.1',
        'nginx1.15.2',
        'nginx1.15.3',
        'nginx1.15.4',
        'nginx1.15.5',
        'nginx1.15.6',
        'nginx1.15.7',
        'nginx1.15.8',
        'nginx1.15.9',
        'nginx1.16.1',
        'nginx1.16.2',
        'nginx1.16.3',
        'nginx1.16.4',
        'nginx1.16.5',
        'nginx1.16.6',
        'nginx1.16.7',
        'nginx1.16.8',
        'nginx1.16.9',
        'nginx1.17.1',
        'nginx1.17.2',
        'nginx1.17.3',
        'nginx1.17.4',
        'nginx1.17.5',
        'nginx1.17.6',
        'nginx1.17.7',
        'nginx1.17.8',
        'nginx1.17.9',
        'nginx1.18.1',
        'nginx1.18.2',
        'nginx1.18.3',
        'nginx1.18.4',
        'nginx1.18.5',
        'nginx1.18.6',
        'nginx1.18.7',
        'nginx1.18.8',
        'nginx1.18.9',
        'nginx1.19.1',
        'nginx1.19.2',
        'nginx1.19.3',
        'nginx1.19.4',
        'nginx1.19.5',
        'nginx1.19.6',
        'nginx1.19.7',
        'nginx1.19.8',
        'nginx1.19.9',
        'nginx1.20.1',
        'nginx1.20.2',
        'nginx1.20.3',
        'nginx1.20.4',
        'nginx1.20.5',
        'nginx1.20.6',
        'nginx1.20.7',
        'nginx1.20.8',
        'nginx1.20.9',
        'nginx1.21.1',
        'nginx1.21.2',
        'nginx1.21.3',
        'nginx1.21.4',
        'nginx1.21.5',
        'nginx1.21.6',
        'nginx1.21.7',
        'nginx1.21.8',
        'nginx1.21.9',
    ],
    'login_images' => [
        [
            'name' => '默认',
            'value' => '/static/back/login-back00.jpg',
        ],
        [
            'name' => '5G相关',
            'value' => '/static/back/login-back01.jpg',
        ],
        [
            'name' => '蓝色汽车',
            'value' => '/static/back/login-back02.jpg',
        ],
        [
            'name' => '新能源汽车',
            'value' => '/static/back/login-back03.jpg',
        ],
        [
            'name' => '地图波点',
            'value' => '/static/back/login-back04.jpg',
        ],
        [
            'name' => '蓝色电力',
            'value' => '/static/back/login-back05.jpg',
        ],
        [
            'name' => '教学课程',
            'value' => '/static/back/login-back06.jpg',
        ],
        [
            'name' => '蓝色城市',
            'value' => '/static/back/login-back07.jpg',
        ],
        [
            'name' => '蓝色数据',
            'value' => '/static/back/login-back08.jpg',
        ],
        [
            'name' => '蓝色城市二',
            'value' => '/static/back/login-back09.jpg',
        ],
        [
            'name' => '智能互联',
            'value' => '/static/back/login-back10.jpg',
        ],
        [
            'name' => '智能通讯',
            'value' => '/static/back/login-back11.jpg',
        ],
        [
            'name' => '化学制药',
            'value' => '/static/back/login-back12.jpg',
        ],
        [
            'name' => '绿色城市',
            'value' => '/static/back/login-back13.jpg',
        ],
        [
            'name' => '工程安全',
            'value' => '/static/back/login-back14.jpg',
        ],
        [
            'name' => '医疗DNA',
            'value' => '/static/back/login-back15.jpg',
        ],
        [
            'name' => '科技VR',
            'value' => '/static/back/login-back16.jpg',
        ],
        [
            'name' => '艺术舞台',
            'value' => '/static/back/login-back17.jpg',
        ],
        [
            'name' => '食品安全',
            'value' => '/static/back/login-back18.jpg',
        ],
        [
            'name' => '物流运输',
            'value' => '/static/back/login-back19.jpg',
        ],
        [
            'name' => '风力电能',
            'value' => '/static/back/login-back20.jpg',
        ],
        [
            'name' => '生物基因链',
            'value' => '/static/back/login-back21.jpg',
        ],
        [
            'name' => '节能低碳',
            'value' => '/static/back/login-back22.jpg',
        ],
        [
            'name' => '绿色家园',
            'value' => '/static/back/login-back23.jpg',
        ],
        [
            'name' => '信息安全',
            'value' => '/static/back/login-back24.jpg',
        ],
        [
            'name' => '城市大数据',
            'value' => '/static/back/login-back25.jpg',
        ],
        [
            'name' => '商务办公',
            'value' => '/static/back/login-back26.jpg',
        ],
        [
            'name' => '网络设备',
            'value' => '/static/back/login-back27.jpg',
        ],
        [
            'name' => '汽车美容',
            'value' => '/static/back/login-back28.jpg',
        ],
        [
            'name' => '自助洗车',
            'value' => '/static/back/login-back29.jpg',
        ],
    ],
];
